version: '3.8'

services:
  shmarql_dev:
    # image: ghcr.io/epoz/shmarql:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shmarql_dev
    ports:
      - "8000:8000"
    volumes:
      - ${PWD_VOLUME}:/data
      - ../dataria/app/data_oxigraph:/store
    # environment:
    #   - DEBUG=${DEBUG}
    #   - FTS_FILEPATH=${FTS_FILEPATH}
    #   - RDF2VEC_FILEPATH=${RDF2VEC_FILEPATH}
    #   - DATA_LOAD_PATHS=${DATA_LOAD_PATHS}
    #   - SCHEME=${SCHEME}
    #   - DOMAIN=${DOMAIN}
    env_file:
      - ./.env