site_name: SHMARQL
site_url: https://shmarql.com/
repo_url: https://github.com/epoz/shmarql
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: teal
    accent: pink
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - navigation.top
    - header.autohide
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - shmarql
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      use_pygments: true
      pygments_lang_class: true      
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
extra_javascript:
  - javascripts/extra.js
nav:
  - Introduction: index.md
  - Advanced Searching: fizzysearch.md
  - Configuration:
    - List of Configuration Options: configuration.md
    - With existing websites: proxy.md
    - Using other triplestores: endpoints.md
